version: '2.2'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/nginx/ssl/catalyst-soar.com.cer:ro
      - ./key.pem:/etc/nginx/ssl/catalyst-soar.com.key:ro
    ports: [ "80:80", "443:443", "9002:9002" ]
    depends_on: [ catalyst ]
    networks: [ catalyst ]

  catalyst:
    environment:
      EXTERNAL_ADDRESS: https://localhost
      OIDC_ISSUER: https://localhost:9002/auth/realms/catalyst
